# fly.toml app configuration file generated for musical-memory-api-v1 on 2025-02-17T14:21:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'musical-memory-api-v1'
primary_region = 'sin'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.headers]]
  for = "/*"
  [http_service.headers.values]
    Access-Control-Allow-Origin = "https://project-overview-app-j1wbaam2.devinapps.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, Origin, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
