# fly.toml app configuration file generated for musical-memory-api-v1 on 2025-02-17T14:21:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'musical-memory-api-v1'
primary_region = 'sin'

[build]
  builder = 'paketobuildpacks/builder:base'

[build.args]
  PYTHON_VERSION = "3.12"

[processes]
  app = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8080"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
